stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "This job compiles code."

test-job:
  stage: test
  script:
    - echo "This job tests the compiled code. It runs when the build stage completes."

test-job_2:
  script:
    - echo "This job also runs in the test stage".

deploy-job:
  stage: deploy
  script:
    - echo "This job deploys the code. It runs when the test stage completes."