version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - spider_web

  python:
    build: .
    restart: always
    depends_on:
      - postgres
    networks:
      - spider_web
    volumes:
      - ./src:/meuBackend

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/application
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres

networks:
  spider_web:
