name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the compose-file
        run: docker-compose up -d --build

  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: inicialização do Container para realizar testes
      run: docker-compose run --entrypoint "npm test" node

  test-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: inicialização do Container para realizar testes
      run: docker-compose run --entrypoint "python manage.py makemigrations && python manage.py migrate && python manage.py test" meu_backend
