name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the compose-file
        working-directory: .
        run: docker-compose up -d --build

  test-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./library_front

    steps:
    - uses: actions/checkout@v3
    
    - name: inicialização do Container para realizar testes
      run: docker-compose up -d --build 
      
    - name: Realização dos testes
      run: docker-compose exec meu_frontend bash -c  "npm install && npm test"

  test-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./library_back

    steps:
    - uses: actions/checkout@v3
    
    - name: inicialização do Container para realizar testes
      run: docker-compose up -d --build 
      
    - name: Realização dos testes
      run: docker-compose exec meu_backend bash -c  "python manage.py makemigrations && python manage.py migrate && python manage.py test"
