name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the compose-file
        run: docker-compose up -d --build

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Usando lint 
      run: docker-compose run --entrypoint "npm run lint src/" node

  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Rodando os testes do front no container
      run: docker-compose run --entrypoint "npm test" node
      env:
        CI: true

  test-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Rodando os testes do back no container
      run: docker-compose run --entrypoint "python manage.py test" meu_backend
