name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the compose-file
        working-directory: .
        run: docker-compose up -d --build

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./library_back

    strategy:
        max-parallel: 4
        matrix:
          python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Usando as versoes do python indicadas
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Rodando testes da aplicacao
      run: |
        python manage.py test
