name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the compose-file
        run: docker-compose up -d --build

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Usando lint 
      run: docker-compose run --entrypoint "npm exec eslint ./src" node

  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Subindo todos os containers
      run: docker-compose up -d --build
    
    - name: Rodando os testes do front
      run: docker exec app_frontend bash -c "CI=true npm test --watchAll=false"

  test-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Rodando os testes do back no container
      run: docker-compose run --entrypoint "python manage.py test" meu_backend
